#!/usr/bin/python
import os,sys,logging,re
import argparse

parser = argparse.ArgumentParser(description='Process attribute names and values')
parser.add_argument('--key', dest="attributes", action='append', help='attribute name to search for')
parser.add_argument('--val', dest="values", action='append', nargs='+', help="attribute value")

args = parser.parse_args()


path = os.getenv("KFS_PATH")
sys.path.append(path)
#from path
from mongo_wrapper import *
import helper



logging.basicConfig(filename=path+'/log',level=logging.DEBUG)
logging.info("Script called")

initialValSet = helper.initialize()


mongo = mongoWrapper(initialValSet['mongo_host'],int(initialValSet['mongo_port']))

search = dict()
for i in range(0,len(args.attributes)):
	search[args.attributes[i]] = {'$in':[re.compile(x) for x in args.values[i]]}


for i in mongo.collection.find(search):
	print i['_id']
	os.system("getfattr -d "+i['_id'][1:])

